### ISSUE TITLE
Can this module also immediately import a new module for use e.g. Import-DSCResource?

### ISSUE THREAD

**Issue by dragon788** [davidobrien1985/DscResources#5]
I left a comment on your initial blog post about this repository, but I am wondering if it would be possible to have this module perform the install and import so that you could immediately use the module that was added, but I'm not sure if this matches the structure of how DSC works.

**Comment by davidobrien1985** [comment]
@dragon788 no, this won't fly with DSC. If the `Import-DscModule` keyword can't find the module then the file won't compile to a `.mof`. This would need to happen in two steps.
